[project]
name = "pqbeam"
version = "0.0.1"
description = "pqbeam coming soon"
readme = "README.md"
license = "MIT"
authors = [{name = "Richard"}]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
